service: news-website

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11

  region: us-east-1

  iam:
    role:
      statements:
        # - Effect: Allow
        #   Action:
        #     - s3:GetObject
        #   Resource:
        #     - "arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME1}/uploads/*"
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:DeleteItem
          Resource: 
            - "arn:aws:dynamodb:*:*:table/EnDyDBTable"
    
  #environment:
  #  S3_BUCKET_NAME1:  'en-seidhi-thaal'



functions:
  news_crawler:
    handler: news_crawler.handler
    name: news_crawler
    events:
      - schedule: cron(10 18 * * ? *)
      #cron(10 18 * * ? *)
      #rate(50 minutes)

  get_item:
    handler: get_item.handler
    events:
      - http: 
          method: GET 
          path: get_item    



      

resources:
  Resources:
    EnDyDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: EnDyDBTable
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: S  
          - AttributeName: section
            AttributeType: S
              
        KeySchema:
          - AttributeName: date
            KeyType: HASH
          - AttributeName: section
            KeyType: RANGE
          
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1      

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true  
