service: news-website

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11

  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME1}/uploads/*"
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Query
      Resource: 
        - "arn:aws:dynamodb:*:*:table/EnDyDBTable"
    
  environment:
    S3_BUCKET_NAME1:  'en-seidhi-thaal'



functions:
  hello:
    handler: handler.hello
    name: hello
    events:
      #- schedule: rate(24 hours)

resources:
  Resources:
    EnDyDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: EnDyDBTable
        AttributeDefinitions:
          - AttributeName: timestamp
            AttributeType: S  
          - AttributeName: section
            AttributeType: S
              
        KeySchema:
          - AttributeName: timestamp
            KeyType: HASH
          - AttributeName: section
            KeyType: RANGE
          
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1      

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true  
