service: news-website

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  region: us-east-1

  iam:
    role:
      statements:
        # - Effect: Allow
        #   Action:
        #     - s3:GetObject
        #   Resource:
        #     - "arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME1}/uploads/*"
        - Effect: Allow
          Action:
            - states:StartExecution
            - lambda:InvokeFunction
          Resource:
            - "*"  
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:DeleteItem
          Resource: 
            - "arn:aws:dynamodb:*:*:table/EnDyDBTable"

 
  #environment:
  #  S3_BUCKET_NAME1:  'en-seidhi-thaal'



functions:
  news_crawler:
    handler: news_crawler.handler
    name: news_crawler
    events:
      - schedule: rate(179 minutes)
      #cron(10 18 * * ? *)
      #rate(50 minutes)

  get_item:
    handler: get_item.handler
    events:
      - http: 
          method: GET 
          path: get_item  

  create_item:
    handler: create_item.handler

stepFunctions:
  stateMachines:
    crawlStateMachine:
      name: crawlStateMachine
      definition:
        StartAt: news_crawler
        States:
          news_crawler:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:339712883099:function:news_crawler
            Next: create_item
         
          create_item:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:339712883099:function:news-website-dev-create_item        
            InputPath: $.Payload
            End: true 
         
resources:
  Resources:
    # EventBridgeRule:
    #   Type: AWS::Events::Rule
    #   Properties:
    #     ScheduledExpression: "rate(17 minutes)"
    #     State: ENABLED
    #     Targets
    #       Arn: arn:aws:states:us-east-1:339712883099:stateMachine:crawlStateMachine
    #       Id: crawlStateMachineTarget

          


    EnDyDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: EnDyDBTable
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: S  
          - AttributeName: section
            AttributeType: S
              
        KeySchema:
          - AttributeName: date
            KeyType: HASH
          - AttributeName: section
            KeyType: RANGE
          
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1      

plugins:
  - serverless-python-requirements
  
  - serverless-step-functions
custom:
  pythonRequirements:
    dockerizePip: true  
